backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articoli"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titolo"
        name: "title"
        widget: "string"
      - label: "Data"
        name: "date"
        widget: "datetime"
      - label: "Descrizione"
        name: "description"
        widget: "string"
      - label: "Contenuto"
        name: "body"
        widget: "markdown"
